	game.AddParticles("particles/ac_impacts_fx.pcf")

	PrecacheParticleSystem("impact_concrete")
	PrecacheParticleSystem("impact_metal")
	PrecacheParticleSystem("impact_computer")
	PrecacheParticleSystem("impact_dirt")
	PrecacheParticleSystem("impact_wood")
	PrecacheParticleSystem("impact_glass")
	PrecacheParticleSystem("impact_antlion")
	RunConsoleCommand("cl_new_impact_effects", "1")