CustomizableWeaponry:addFireSound("CW_AUGA3_FIRE", "weapons/cw_tr09_auga3/fire.wav", 1, 115, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_AUGA3_FIRE_SUPPRESSED", "weapons/cw_tr09_auga3/fire_suppressed.wav", 1, 90, CHAN_STATIC)

CustomizableWeaponry:addFireSound("CW_AUGA3_LONGBARREL_FIRE", "weapons/cw_tr09_auga3/lngbrl_fire.wav", 1, 115, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_AUGA3_LONGBARREL_FIRE_SUPPRESSED", "weapons/cw_tr09_auga3/lngbrl_fire_suppressed.wav", 1, 90, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_AUGA3_CLOTH", "weapons/cw_tr09_auga3/cloth.wav")
CustomizableWeaponry:addReloadSound("CW_AUGA3_DEPLOY", "weapons/cw_tr09_auga3/deploy.wav")
CustomizableWeaponry:addReloadSound("CW_AUGA3_MAGRELEASE", "weapons/cw_tr09_auga3/magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_AUGA3_MAGOUT", "weapons/cw_tr09_auga3/magout.wav")
CustomizableWeaponry:addReloadSound("CW_AUGA3_MAGIN", "weapons/cw_tr09_auga3/magin.wav")
CustomizableWeaponry:addReloadSound("CW_AUGA3_MAGHIT", "weapons/cw_tr09_auga3/hit.wav")
CustomizableWeaponry:addReloadSound("CW_AUGA3_MAGDROP", "weapons/cw_tr09_auga3/magdrop.wav")
CustomizableWeaponry:addReloadSound("CW_AUGA3_BOLTPULL", "weapons/cw_tr09_auga3/boltpull.wav")
CustomizableWeaponry:addReloadSound("CW_AUGA3_BOLTRELEASE", "weapons/cw_tr09_auga3/boltrelease.wav")